### PR TITLE
Thermal Expansion: Converted pages to markdown

### PR DESCRIPTION
**Pull request by 016Nojr**

### CODE REVIEW

**Comment by 016Nojr** [comment]
@Tonius Not sure how this will affect your recent commit, but I had to change something in the recipes-crafting files in this PR

**Comment by 016Nojr** [comment]
Is there a reason this isnt merged yet? @Tonius

**Comment by Tonius** [comment]
To be honest, PRs like this one aren't really needed. I will soon be rewriting all the TE pages (after I'm done with TF) and will be cleaning up / converting to Markdown along the way.

Sorry if this was a lot of work for you :/

**Comment by 016Nojr** [comment]
It wasnt that much work, to avoid this happening, tell me what I can do @Tonius :)

**Comment by Tonius** [comment]
I can't really think of anything big right now that I won't soon be working on myself. Minor fixes/tweaks are always welcome though.

**Pull request closed without merging**
